#!/bin/sh

# [K]2022
# https://github.com/kongfl888

source /usr/share/my-dnshelper/comm

#debug
EA=1

[ "$EA" = "1" ] || exit 0
[ "$S" = "1" ] && SPath=$EPath/Rules
chmod 0744 $updatelog >/dev/null 2>&1
udt1=`cat $updatelog 2>/dev/null`

[ $(ls -l /usr/share/my-dnshelper/rulesmaker | grep -c "rwx" 2>/dev/null) -eq 0 ] && chmod 0774 /usr/share/my-dnshelper/*

echo "`eval $D` Check Subscribe Rules Update" >> $Logfile
echo "0" > $updatelog

check_lock

sh /usr/share/my-dnshelper/rulesmaker -u >> $Logfile 2>/dev/null

udt2=`cat $updatelog 2>/dev/null`
udx1=`date -d "$udt1" +%s`
udx2=`date -d "$udt2" +%s`

if [ -z "$udt2" -o "$udt2" == "0" -o $udx2 -lt $udx1 ];then
	echo $udt1 > $updatelog
	exit 1
fi

echo "`eval $D` Reload Rules" >> $Logfile

rs_dnsmasq

exit 0
