#!/bin/sh

# [K]2022
# https://github.com/kongfl888

source /usr/share/my-dnshelper/comm

Helpthis() {
DATE_HMS=`date +%H:%M:%S`
DATE_Y=`date +%Y`
DATE="$DATE_Ymd $DATE_HMS"
echo "
Hi Master, I'm your dnshelper. This one of my waiters for you.

usage: waiter [OPTION]

...

I am sorry.

He's a little shy and not ready.

...

It is juest a part of me. You still need a luci application.
Thank you for coming to look at me. I'm very happy.
By MY-Dnshelper on $DATE

[K] $DATE_Y
You can contact my Founder via this link: https://github.com/kongfl888
"
exit 0
}

Pa=${1}

crules=$SPath/rules.conf
cwhite=$SPath/white.txt
chosts=$SPath/hosts.conf
countf=$SPath/count.txt
ifc=0
iac=0
ihc=0

check_bin(){
	[ -f "/usr/bin/my-dnshelper" -a "$EA" == "1" ] || return
	local p=`ps|grep "/usr/bin/my-dnshelper"|sed "/grep/d"`
	[ -z "$p" ] && /etc/init.d/my-dnshelper start
}

clear_rule(){
	read_count
	if [ "$1" == "1" ];then
		echo -n > $crules
		ifc=0
	elif [ "$1" == "2" ];then
		echo -n > $cwhite
		iac=0
	elif [ "$1" == "3" ];then
		echo -n > $chosts
		if [ "$GH" == "1" -a -s $EPath/github.mdhp ];then
			touch $SPath/hosts.conf
			cat $EPath/github.mdhp >> $SPath/hosts.conf
			sort_file $SPath/hosts.conf
		fi
		ihc=0
	fi
	echo "$ifc,$iac,$ihc" > $countf
	if [ "$(cat $updatelog 2>/dev/null)" == "0" ]; then
		rm -f $updatelog
	fi
	echo "`eval $D` Rules have changed." >> $Logfile
	echo "`eval $D` Dnsmasq reload." >> $Logfile
	/etc/init.d/dnsmasq reload 2>/dev/null
	echo "$?"
}

get_dnsonline(){
	local rc=0
	if [ "$dnsdetect" == "1" ]; then
		which curl >/dev/null 2>&1 || rc=1
		if [ $rc -eq 1 ];then
			echo ""
		else
			local rurl=`curl --connect-timeout 5 -m 10 -kLfs http://nstool.netease.com | grep -oE "http.*[a-zA-Z]\/"`
			local txt=`curl --connect-timeout 5 -m 10 -kLfs  $rurl | grep -oE "[Ii][pP].*[DNSdns]+.*\.\d+.*<br>"`
			if [ -z "$txt" ];then
				echo ""
			else
				local ip=`echo $txt|grep -oE "[0-9]+(\.[0-9]+){3}" |head -n 1`
				local ds=`echo $txt|grep -oE "[0-9]+(\.[0-9]+){3}" |sed -n "2p"`
				echo '<p>Detect DNS：IP - '$ip'| DNS - '$ds'</p>'
			fi
		fi
	else
		echo ""
	fi
}

case $Pa in
	"--help")
	Helpthis
	;;
	"-m"|"--dnsmasq")
	echo "Dnsmasq `dnsmasq --version | grep -oE 'v.*\d+(\.\d+)+'| grep -oE '\d+(\.\d+)*'`"
	;;
	"-d"|"--doh")
	hv=`opkg list-installed https-dns-proxy 2>/dev/null`
	[ -n "$hv" ] && echo "`echo $hv | sed -e 's/https-dns-proxy/core/' -e 's/ -/ version: /'`" || echo "https-dns-proxy is not installed"
	;;
	"-f"|"--filter")
	get_count $crules
	;;
	"-a"|"--allow")
	get_count $cwhite
	;;
	"-h"|"--hosts")
	get_count $chosts
	;;
	"-u"|"--update")
	sh /usr/share/my-dnshelper/uprules &
	echo "0"
	;;
	"--port")
	echo $(get_ports) |sed 's/ /,/g'
	;;
	"--xf")
	clear_rule 1
	;;
	"--xw")
	clear_rule 2
	;;
	"--xh")
	clear_rule 3
	;;
	"--dns")
	get_dnsonline
	;;
	*)
	Helpthis
	;;
esac
check_bin
exit 0
