#20201023
name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/check-adgh.yml'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build the IPK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Docker Build
      run: |
        git clone --single-branch https://github.com/kongfl888/luci-app-adguardhome.git
        mkdir bin
        PKG_DIR=luci-app-adguardhome
        cp -rf ./${PKG_DIR} ./bin/
        sed -i '/LUCI_DEPENDS/d' ./bin/${PKG_DIR}/Makefile
        sed -i 's/include ..\/..\/luci.mk/include $(TOPDIR)\/feeds\/luci\/luci.mk/' ./bin/${PKG_DIR}/Makefile
        docker pull openwrtorg/sdk:x86-64-21.02-SNAPSHOT
        docker run --rm -u root -v "$(pwd)"/bin/:/home/build/openwrt/bin -v ${{ github.workspace }}/.github/workflows:/home/build/workflows openwrtorg/sdk:x86-64-21.02-SNAPSHOT /bin/sh /home/build/workflows/build-test.sh ${PKG_DIR}
    - name: Upload app
      uses: actions/upload-artifact@v2
      with:
        name: pack
        path: ./bin/packages/x86_64/base/*adg*
        if-no-files-found: error
    - name: Upload Log
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: buildlog
        path: bin/logs.tar.xz
